#FROM jboss/keycloak:16.1.1
#https://quay.io/repository/keycloak/keycloak?tab=info
FROM  quay.io/keycloak/keycloak:19.0.2

# COPY tls.crt /etc/x509/https/tls.crt
# COPY tls.key /etc/x509/https/tls.key