name: CI

on:
  push:
    branches:
      - sample

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 118.27.18.23
          username: root
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |

            export DOMAIN=udemy-flask-sample.top
            export API_DOMAIN=api.udemy-flask-sample.top
            export KEY_DOMAIN=auth.udemy-flask-sample.top
            export MAIL=xxxx

            # 環境
            export ENV=PROD

            # mysqlの設定
            export ROOT=hogehoge
            export DB=hoge
            export DB_USER=hogehoge
            export DB_PASS=hogehoge

            # セッションデータを保存するために必要
            export SECRET_KEY=hogepeke

            # CSRF対策
            export CSRF_SECRET=pekehoge

            # keycloak 
            export KEYCLOAK_DB=keycloaks
            export KEYCLOAK_DB_USER=keycloak
            export KEYCLOAK_DB_PASS=hogepeke
            export KEYCLOAK_ADMIN_PASSWORD=hogepeke

            # oauth2proxy
            export COOKIE_SEC=0123456789012345678a901234567891

            # keycloak 発行後
            export CLIENT_ID=flasks
            export CLIENT_SECRET=G6xqdoC33HytUhEi0vjvUgKMSGZ2QXYL

            # JWTデコードするためのキー
            export JWT_PUBLIC_KEY=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArDbO7AsVe/0+vD2ot2gy1/Kr0cNaSBR+6jYSQsQ6kQXhdCHW7mSnjmrHAkbdwca5oDiGWu/dw3X7SDMS32dLZzDJY1qp8V91kkQP9IK41rmgM2Hf2K8/smrR7eXXRrwjUIW0W0I1VcM7inbF728c0ToVuKsLBK2iIAi0Jx1KiUNx2OvLyRgKQNb6SjgF2nELCrkwJ2OHmb9NYR6FqKkp5w1TFyOS7ULFAdLJtAJFYpxNlGe0xuu89l0xh8U4LOkv+hcnq7TsNk62uYIt1TjvUissfhgW2ryoQvPWl+bxuSs9X+1vLqiFmqQyo816QYJWm3MTP/E4O4PsFDl/wpBDTQIDAQAB

            # gmail
            export MAIL_USERNAME=flaks.udemy@gmail.com
            export MAIL_PASSWORD=lvknbziasyiqcvea

            cd udemy-flask-sample/ && git pull && docker-compose build && docker-compose up -d
            
            docker exec udemy-flask-sample_app_api_1 /bin/bash -c 'pytest -s tests/test_hoge.py'
